apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mssql-db-secret
  namespace: tools
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgApy8DCJMX9RNRkBe9tXcuWwZuAECgAd68Y7YQzcNBBPhYmORK278wfzMkJqclElw86Bvf+4ggc8D7HlfDnDL31gFUAY6VZsAJYDPjblC1+46QD61GP5dAU6aCN8nR/XPBWy/B7wP/lb8O+2C+xp6qHldyEbohkdH1KPmkCyIO2s09N8o8ktDT0OVSyxpTQnFhheDv8Wrgw3m51Dsxsobr4WLGRfANT4aa+4Jy7q5Cgs1A+soUcyd2wJ63f9W9/CE1xj3QtGh9ClKSmYDxYJznxfhe8OVQ9H6uMSVKG5BqDgzXMmPYV3WcnU12O5MZTjWjuO+mZdikA/sag2cuTnmiGKWCEwdnk+u/MBHzxN78oC2NFcKp9FaB9rlxtUeoHq2P2CWtRpjqY8LZB85Yjkm1fGSGiB0j28h9Tqrbcj6mfDEPTjUKGMNME7RxD9JND0Ts44avNLrAgJEhKWc397QBMPcMKfWW2MgOfulHwfn8dVLB5lk3OaWspXhKTHw2WefNGh4GqODOnjAoTp9sQU4GiHR5dM+f0PFfLbJYp/SfAzxXX37nKB3alMQHHL40c21O6eQtO7ofDsJCaG6HiqQJXKDMhHAZvrIdXOe1NBFjFWA8qn4SgWMNWeFSsKbKdoR42lzYw9PZjxNM/3vHLOilIaNq8xXjlSDH3H9l+mLZIXkBv6lMxnVZO3vA3yadZtU2VOHCDmCk64A==
  template:
    metadata:
      creationTimestamp: null
      name: mssql-db-secret
      namespace: tools
    type: Opaque

