
---
# Source: ibm-sfg-b2bi/charts/ibm-sfg-prod/templates/cleanup/cleanup-role.yaml
# (C) Copyright 2019 Syncsort Incorporated. All rights reserved.



apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "sfg-cleanup-role"
  namespace: tools
  labels:
    app.kubernetes.io/name: "sfg"
    helm.sh/chart: "ibm-sfg-prod"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "release-name"
    release: "release-name"
    app.kubernetes.io/component: "cleanup-role"
  annotations:
        "helm.sh/hook": "pre-upgrade, post-delete"
        "helm.sh/hook-weight": "1"
        #"helm.sh/hook-delete-policy": "hook-succeeded, before-hook-creation"

rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - get
  - list
  - delete