
---
# Source: ibm-sfg-b2bi/charts/ibm-sfg-prod/templates/asi-statefulset.yaml
# (C) Copyright 2019 Syncsort Incorporated. All rights reserved.


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "sfg-asi-server"
  labels:
    tier: backend
    app.kubernetes.io/name: "sfg"
    helm.sh/chart: "ibm-sfg-prod"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "release-name"
    release: "release-name"
    app.kubernetes.io/component: "asi-server"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: "sfg"
      helm.sh/chart: "ibm-sfg-prod"
      app.kubernetes.io/managed-by: "Helm"
      app.kubernetes.io/instance: "release-name"
      release: "release-name"
      app.kubernetes.io/component: "asi-server"
  serviceName: "sfg-cluster-svc"
  template:
    metadata:
      labels:
        tier: backend
        app.kubernetes.io/name: "sfg"
        helm.sh/chart: "ibm-sfg-prod"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/instance: "release-name"
        release: "release-name"
        app.kubernetes.io/component: "asi-server"          
      annotations:        
        productID: "0acf190850514574bb48a3d0ac0341e6"
        productName: "IBM Sterling File Gateway Enterprise Edition Certified Container"
        productVersion: "6.1.0.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: asi
    spec:
      serviceAccountName: b2bi
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        
        fsGroup: 1010
        runAsNonRoot: true
        runAsUser: 1010
        supplementalGroups:
        - 65534
      volumes: 
        - name: resources
          persistentVolumeClaim:
            claimName: "ibm-sfg-b2bi-sfg-resources"   
        - name: logs
          persistentVolumeClaim:
            claimName: "ibm-sfg-b2bi-sfg-logs"
        - name: "documents"
          persistentVolumeClaim:
            claimName: "ibm-sfg-b2bi-sfg-documents"
        - name: configmap-resources-volume
          configMap:
           name: "sfg-config"
        - name: configmap-properties-volume
          configMap:
           name: "sfg-config-property"
        - name: configmap-dummy-properties-volume
          configMap:
           name: "sfg-config-dummy-property"
        # extra configured volumes
      imagePullSecrets:
        - name: ibm-entitlement-key
      containers:
        - name: "asi"
          image: "cp.icr.io/cp/ibm-sfg/sfg:6.1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 50000
              protocol: TCP
            - name: soa
              containerPort: 50040
              protocol: TCP
            - name: soassl
              containerPort: 50041
              protocol: TCP
            - name: lwfw-soap
              containerPort: 5580
              protocol: TCP
            - name: adapter-1
              containerPort: 30201
              protocol: TCP
            
            
            
            - name: adapters-1
              containerPort: 30301
              protocol: TCP
            
            - name: adapters-2
              containerPort: 30302
              protocol: TCP
            
            - name: adapters-3
              containerPort: 30303
              protocol: TCP
            
            - name: adapters-4
              containerPort: 30304
              protocol: TCP
            
            - name: adapters-5
              containerPort: 30305
              protocol: TCP
          env:
            - name: "TZ"
              value: "UTC"
            - name: "LICENSE"
              value: "accept"
            - name: "JAVA_TOOL_OPTIONS"
              value: ""
            - name: "NODE_NUMBER_IN_HOST"
              value: "true"
            - name: "SANDBOX_CC_INSTALL"
              value: "true"
            - name: "SANDBOX_CC_NODE_NAME"
              value: "node_b2biNodeNumber_"
            - name: "SERVER_TYPE"
              value: "asi"
            - name: "IS_SEAS_ENABLED"
              value: "false"
            - name: "SEAS_VERSION"
              value: "1.0"
            - name: "SANDBOX_ASI_SERVICE_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "SANDBOX_ASI_SERVICE_PORT"
              value: "50000"
            - name: "SANDBOX_API_GATEWAY_IP"
              value: "api.itzroks-3100027vrr-mi7r0j-4b4a324f027aea19c5cbc0c3275c4656-0000.us-south.containers.appdomain.cloud"
            - name: "SANDBOX_API_GATEWAY_PORT"
              value: "443"
            - name: "SANDBOX_MYFG_PROTOCOL"
              value: "https"
            - name: "LIBERTY_EXTERNAL_PROTOCOL"
              value: "https"
            - name: "LIBERTY_EXTERNAL_HOST"
              value: "api.itzroks-3100027vrr-mi7r0j-4b4a324f027aea19c5cbc0c3275c4656-0000.us-south.containers.appdomain.cloud"
            - name: "LIBERTY_EXTERNAL_PORT"
              value: "443"
            - name: "SANDBOX_EXT_HOST_ADDR"
              value: "asi.itzroks-3100027vrr-mi7r0j-4b4a324f027aea19c5cbc0c3275c4656-0000.us-south.containers.appdomain.cloud"
            - name: "SANDBOX_EXT_ACCESS_PORT"
              value: "443"
            - name: "SANDBOX_EXT_ACCESS_PROTOCOL"
              value: https
            - name: "SANDBOX_EXT_SOA_PORT"
              value: "443"
            
            - name: "UPGRADE_COMPATIBILITY_VERIFIED"
              value: "false"
            - name: "ENABLE_APP_LOG_ON_CONSOLE"
              value: "false"
#            - name: "NODE_NUMBER"
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.annotations['spec.pod.beta.kubernetes.io/statefulset-index']
            - name: "PROPERTY_ops_heartbeat"
              value: "180"
            - name: "PROPERTY_ops_nodeStatusCheckInterval"
              value: "30"
            - name: "PROPERTY_ops_OpsServerU2022commandTimeout"
              value: "180"
            - name: "PROPERTY_ui_alternate_url_prefix"
              value: "&WEBAPP_PROTOCOL;://&HOST_NAME;:&WEBAPP_LIST_PORT;"
            - name: "SANDBOX_JGROUP_CLUSTER_MCAST1_DNS_QUERY"
              value: "_mcast1._tcp.sfg-cluster-svc.tools"
            - name: "SANDBOX_JGROUP_CLUSTER_MCAST2_DNS_QUERY"
              value: "_mcast2._tcp.sfg-cluster-svc.tools"
            - name: "SANDBOX_JGROUP_CLUSTER_MCAST3_DNS_QUERY"
              value: "_mcast3._tcp.sfg-cluster-svc.tools"
            - name: "SANDBOX_JGROUP_CLUSTER_DNS_RECORD_TYPE"
              value: "SRV"
          envFrom:
          
          - secretRef:
                name: "b2b-system-passphrase-secret"


          - secretRef:
                name: "b2b-db-secret"


          - secretRef:
                name: "b2b-jms-secret"


          volumeMounts: 
            - name: resources
              mountPath: /ibm/resources  
            - name: logs
              mountPath: /ibm/trace  
            - name: documents
              mountPath: /ibm/b2bi/install/documents
            
            - name: configmap-resources-volume
              mountPath: /ibm/resources/setup.cfg
              subPath: setup.cfg
            - name: configmap-properties-volume
              mountPath: /ibm/b2bi/ext-resources/properties
            - name: configmap-dummy-properties-volume
              mountPath: /ibm/b2bi/ext-resources/dummy-properties
            
          args: ["b2bi_run", "b2bi"]
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsUser: 1010
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - /ibm/b2bi/install/bin/b2biLivelinessCheck.sh asi
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /dashboard/
              port: 50000
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 60
      affinity:        
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:      
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          preferredDuringSchedulingIgnoredDuringExecution:        
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  
          preferredDuringSchedulingIgnoredDuringExecution:        
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  
          preferredDuringSchedulingIgnoredDuringExecution: