
---
# Source: ibm-sfg-b2bi/charts/ibm-sfg-prod/templates/db-setup-job.yaml
# (C) Copyright 2019 Syncsort Incorporated. All rights reserved.


apiVersion: batch/v1
kind: Job
metadata:
    name: "sfg-db-setup"
    annotations:
        # This is what defines this resource as a hook. Without this line, the
        # job is considered part of the release.
        "helm.sh/hook": "pre-install, pre-upgrade"
        "helm.sh/hook-weight": "2"
        #"helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    labels:
        app.kubernetes.io/name: "sfg"
        helm.sh/chart: "ibm-sfg-prod"
        app.kubernetes.io/managed-by: "Helm"
        
        
        app.kubernetes.io/component: "db-setup"
spec:
    backoffLimit: 1
    template:
        metadata:
            name: "sfg-db-setup"
            labels:
              app.kubernetes.io/name: "sfg"
              helm.sh/chart: "ibm-sfg-prod"
              app.kubernetes.io/managed-by: "Helm"
              
              
              app.kubernetes.io/component: "db-setup"
            annotations:              
              productID: "0acf190850514574bb48a3d0ac0341e6"
              productName: "IBM Sterling File Gateway Enterprise Edition Certified Container"
              productVersion: "6.1.0.0"
              productMetric: "FREE"
              productChargedContainers: db-setup
        spec:
            serviceAccountName: b2bi
            hostNetwork: false
            hostPID: false
            hostIPC: false
            securityContext:
              
              fsGroup: 1010
              runAsNonRoot: true
              runAsUser: 1010
              supplementalGroups:
              - 65534
            volumes:
                - name: "resources"
                  persistentVolumeClaim:
                    claimName: "ibm-sfg-b2bi-sfg-resources"
                - name: configmap-resources-volume
                  configMap:
                    name: "sfg-config"
            imagePullSecrets:
              - name: ibm-entitlement-key
            containers:
                - name: "db-setup"
                  resources:
                    limits:
                      cpu: 4000m
                      memory: 8Gi
                    requests:
                      cpu: 2000m
                      memory: 4Gi
                  image: "cp.icr.io/cp/ibm-sfg/sfg:6.1.0.0"
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: "TZ"
                      value: "UTC"
                    - name: "LICENSE"
                      value: "accept"
                    - name: "UPGRADE_COMPATIBILITY_VERIFIED"
                      value: "false"
                    - name: "SANDBOX_CC_INSTALL"
                      value: "true"
                  envFrom:

                  - secretRef:
                        name: "b2b-system-passphrase-secret"


                  - secretRef:
                        name: "b2b-db-secret"


                  - secretRef:
                        name: "b2b-jms-secret"


                  securityContext:
                    
                    allowPrivilegeEscalation: false
                    capabilities:
                      drop:
                      - ALL
                    privileged: false
                    readOnlyRootFilesystem: false
                    runAsUser: 1010
                  volumeMounts:
                    - name: resources
                      mountPath: /ibm/resources
                    - name: configmap-resources-volume
                      mountPath: /ibm/resources/setup.cfg
                      subPath: setup.cfg
                  args: ["b2bi_setup", "deploy_db"]
            restartPolicy: Never
            affinity:              
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                      - amd64
