resources:
- ./ibm-queuemanager-instance.yaml
- ./mqcm.yaml
# generatorOptions:
#   annotations:
#     argocd.argoproj.io/sync-wave: '200'
#   name: msqsc-configmap-inst
# configMapGenerator:
# - name: msqsc-configmap-inst
#   behavior: create
#   files:
#   - msqsc-configmap-inst.yaml