resources:
- ./ibm-queuemanager-instance.yaml
# - ./msqsc-configmap.yaml
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: '200'
configMapGenerator:
- name: my-configmap
  behavior: create
  files:
  - msqsc-configmap.yaml