resources:
- ./ibm-queuemanager-instance.yaml
# - ./mqcm.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: '200'
configMapGenerator:
- name: mqcm
  behavior: build
  files:
  - static-definitions.mqsc