ibm-qm-instance:
  metadata:
    name: ibm-queuemanager-instance
    namespace: tools
  spec:
    name: ibm-queuemanager-instance
    license:
      accept: true
      license: L-APIG-BYHCL7
      use: Development
    version: 9.2.3.0-r1
    storageClassName: standard
