ppc-qm:
  metadata:
    name: ppcqm
    namespace: tools
  spec:
    name: ppcqm
    license:
      accept: true
      license: L-APIG-BYHCL7
      metric: ProcessorValueUnit
      use: Development
    version: 9.2.5.0-r2
    storageClassName: azure-file
